// Tarot card data — Major Arcana + select Minor for variety
window.TAROT_DECK = [
  { id: 0, num: "0", name: "The Fool", suit: "major", upright: ["beginnings", "leap", "innocence"], reversed: ["recklessness", "foolishness"],
    meaning: "an open road and an unpacked bag. you don't have a plan and that is the plan." },
  { id: 1, num: "I", name: "The Magician", suit: "major", upright: ["will", "skill", "manifestation"], reversed: ["manipulation", "untapped"],
    meaning: "the tools are already on the table. arrange them and start." },
  { id: 2, num: "II", name: "The High Priestess", suit: "major", upright: ["intuition", "patience", "the inner room"], reversed: ["secrets", "withdrawal"],
    meaning: "you know more than you've said out loud. sit with it for a bit." },
  { id: 3, num: "III", name: "The Empress", suit: "major", upright: ["abundance", "softness", "growth"], reversed: ["smother", "stagnant"],
    meaning: "tend to things gently. they grow if left alone with sun and water." },
  { id: 4, num: "IV", name: "The Emperor", suit: "major", upright: ["structure", "authority", "boundary"], reversed: ["rigidity", "overreach"],
    meaning: "build a frame. inside the frame, you can do almost anything." },
  { id: 5, num: "V", name: "The Hierophant", suit: "major", upright: ["tradition", "study", "doctrine"], reversed: ["dogma", "rebellion"],
    meaning: "old methods exist for a reason. learn them before you break them." },
  { id: 6, num: "VI", name: "The Lovers", suit: "major", upright: ["choice", "union", "alignment"], reversed: ["mismatch", "indecision"],
    meaning: "two paths are not equal even when they look it. pick on values, not optics." },
  { id: 7, num: "VII", name: "The Chariot", suit: "major", upright: ["drive", "control", "victory"], reversed: ["scattered", "stalled"],
    meaning: "two horses pulling opposite ways still moves the cart, just slower." },
  { id: 8, num: "VIII", name: "Strength", suit: "major", upright: ["courage", "patience", "soft power"], reversed: ["self-doubt", "force"],
    meaning: "the lion responds to a low voice, not a raised one." },
  { id: 9, num: "IX", name: "The Hermit", suit: "major", upright: ["solitude", "lantern", "study"], reversed: ["isolation", "stuck"],
    meaning: "go down the mountain alone for a while. bring back what you find." },
  { id: 10, num: "X", name: "Wheel of Fortune", suit: "major", upright: ["cycle", "luck", "turning"], reversed: ["resistance", "delay"],
    meaning: "the wheel turns whether you push it or not. read the moment." },
  { id: 11, num: "XI", name: "Justice", suit: "major", upright: ["balance", "truth", "law"], reversed: ["bias", "evasion"],
    meaning: "the scales don't care about your story. weigh honestly." },
  { id: 12, num: "XII", name: "The Hanged Man", suit: "major", upright: ["pause", "reframe", "surrender"], reversed: ["stalling", "martyrdom"],
    meaning: "a problem turned upside down often shows its seams." },
  { id: 13, num: "XIII", name: "Death", suit: "major", upright: ["ending", "transition", "shed"], reversed: ["clinging", "fear"],
    meaning: "not the literal kind. something is over. let it be over." },
  { id: 14, num: "XIV", name: "Temperance", suit: "major", upright: ["blend", "moderation", "patience"], reversed: ["excess", "imbalance"],
    meaning: "the right amount of two ingredients makes a third thing." },
  { id: 15, num: "XV", name: "The Devil", suit: "major", upright: ["attachment", "shadow", "appetite"], reversed: ["release", "awakening"],
    meaning: "the chains are loose. you put them on yourself; you can take them off." },
  { id: 16, num: "XVI", name: "The Tower", suit: "major", upright: ["upheaval", "revelation", "collapse"], reversed: ["averted", "fear of change"],
    meaning: "what was built on a bad foundation is coming down. let it." },
  { id: 17, num: "XVII", name: "The Star", suit: "major", upright: ["hope", "renewal", "clarity"], reversed: ["dim", "discouraged"],
    meaning: "after the storm, the small lights look very bright. follow one." },
  { id: 18, num: "XVIII", name: "The Moon", suit: "major", upright: ["dream", "illusion", "tide"], reversed: ["clarity", "release"],
    meaning: "not everything you see at night is real. wait until morning before you decide." },
  { id: 19, num: "XIX", name: "The Sun", suit: "major", upright: ["joy", "vitality", "clarity"], reversed: ["dimmed", "delayed"],
    meaning: "permission to enjoy a thing without ironizing it." },
  { id: 20, num: "XX", name: "Judgement", suit: "major", upright: ["awakening", "reckoning", "call"], reversed: ["doubt", "self-judgment"],
    meaning: "you hear the trumpet whether you stand up or not." },
  { id: 21, num: "XXI", name: "The World", suit: "major", upright: ["completion", "wholeness", "arrival"], reversed: ["unfinished", "lingering"],
    meaning: "a thing is finished. mark the moment before starting the next." },
];
